name: project_lms
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ================= ICONS =================
  cupertino_icons: ^1.0.8

  # ================= PACKAGES =================
  file_picker: ^10.3.3
  intl: ^0.20.2
  carousel_slider: ^5.1.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ================= ASSETS =================
  assets:
    - assets/images/
